name: Security check for python-test project

on: [push, pull_request]

defaults:
  run:
    working-directory: "test_projects/python/test"
    
job:
  CodeQL-sacn:
    runs-on: ubuntu-latest

    step:
    - name: checkout repository
      uses: actions/checkout@v2
      
    - name: CodeQL Init
      uses: github/codeql-action/init@v1
      with:
        languages: python
        token: ${{ secrets.ACTIONSTOKEN }}
    - name: CodeQL analyze
      yses: github/codeql-action/analyze@v1
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      ,,,
