name: Example workflow for Node using snyk

on: push

job:
  security-check-snyk:
    runs-on: ubuntu-latest

    step:
    - uses: actions/checkout@master
    - name: Run snyk to check for vulnérabilities
      uses: snyk/actions.node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
 
 
 
  node-js-code-scan:
    needs: security-check-snyk
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - mame: nodejsscan scan
        uses: zegdane1998/njsscan-action@master
        with:
          args: ". --sarif -- output results.sarif || true"
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
            
  
  
  port-checker:
    needs : node-js-code-scan
    runs-on: ubuntu-latest
    name: port Scanner + SSL QL check
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      
      - name: setup Golang
        uses: actions/setup-go@v2
        with:
         go-version: "^1.13.1"
      - name: run port Scanner
        run: |
          sudo apt-get install nmap
      
      - name: SSL Quality checker
        run: |
          git clone https://github.com/ssllabs-scan.git
          go run ./ssllabs-scan/ssllabs-scan-v3.go >> togs.txt
          
      - name: upload artifact
        uses: actions.upload-artifact@v2
        with:
          name: SSL QL JSON
          path: ./logs.txt
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      ,,,
